# Generated by Django 3.1.1 on 2020-10-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaginaweb', '0003_sliderindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('indet', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
