# Generated by Django 3.1.1 on 2020-10-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaginaweb', '0004_misionvision'),
    ]

    operations = [
        migrations.AddField(
            model_name='misionvision',
            name='imagen',
            field=models.ImageField(null=True, upload_to='misionvision'),
        ),
    ]
