# Generated by Django 3.1.1 on 2020-10-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miPaginaweb', '0005_misionvision_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='misionvision',
            name='imagen',
        ),
    ]
