# Generated by Django 3.1.2 on 2020-10-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaginaweb', '0006_remove_misionvision_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('ident', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='galery')),
            ],
        ),
    ]
