# Generated by Django 3.1.1 on 2020-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miPaginaweb', '0002_insumo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('indet', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(null=True, upload_to='car')),
            ],
        ),
    ]
